#!/usr/bin/env python3

# bulk rename files with broken unicode names
# may or may not work for you ¯\_(ツ)_/¯


from argparse import ArgumentParser
from errno import ENOENT
from json import JSONDecodeError
from json import loads as json_load
from pathlib import Path
from re import search as re_search
from re import sub as re_replace
from subprocess import run as run_cmd
from typing import Optional

ASSUME_YES = False


def extract_metadata(file: Path) -> dict[str, Optional[str]]:
    """
    Extract metadata from file
    """
    metadata: dict[str, Optional[str]] = {
        "title": None,
        "album": None
    }

    try:
        ps = run_cmd(["mediainfo", "--Output=JSON", file.as_posix()],
                     check=True,
                     text=True,
                     capture_output=True)
        mediainfo_all = json_load(ps.stdout)

        mediainfo: dict[str, str] = {}
        for track in mediainfo_all["media"]["track"]:
            if track["@type"] == "General":
                mediainfo = track
                break

    except (KeyError, JSONDecodeError) as e:
        print(f"Failed to extract metadata:\n{str(e)}")
        return metadata

    if (title := mediainfo.get("Title")) is not None:
        metadata["title"] = title

    if (album := mediainfo.get("Album")) is not None:
        metadata["album"] = album

    return metadata


def inject_title(stem: str, title: str) -> str:
    """
    Try to replace part of the file stem with the specified title
    Replace all if no valid insertion point could be found
    """
    new: str = ""

    for length in range(len(title), 0, -1):
        title_slice = title[0:length]
        if (idx := stem.find(title_slice)) > -1:
            new = stem[0:idx] + title
            break
    else:
        new = title

    return new


def stem_gc(stem: str) -> str:
    """
    Stem garbage collector
    Collect random trailing symbols that look out of place
    Disc 2 -\\ufffe\\u....- -> Disc 2
    """
    # garbage chars to remove around \\ufffe block
    garbage = r"[-_ ]"

    pattern = garbage + r"*" + r"\\ufffe(?:\\u....)*" + garbage + r"*"
    while (s := re_replace(pattern, r"", stem)) != stem:
        stem = s

    return s


def confirm(prompt: str = "Confirm") -> bool:
    """
    Simple confirmation dialogue
    """
    if ASSUME_YES:
        return True

    while True:
        response = input(prompt + " [Y/n]: ")
        if response.lower() in ["", "y", "yes"]:
            return True
        elif response.lower() in ["n", "no"]:
            return False


def fix_path(path: Path) -> Optional[Path]:
    """
    Detect and fix weird names
    """
    # this escapes all unicode to \uXXXX
    stem_escaped = (path.stem
                    .encode("raw_unicode_escape")
                    .decode("utf-8"))

    # try to find \ufffe substring
    # this indicates a substring with funky utf-16 encoding
    # we need to remove
    if not re_search(r"\\ufffe(?:\\u....)*", stem_escaped):
        return None

    print(f"Found potentially broken path:\n'{path}'")

    if path.is_dir():
        # minor QOL - don't leave trailing whitespace
        # for directories we can't really do anything else
        new_path = path.with_stem(stem_gc(stem_escaped))
    else:
        print("Attempting to use title from metadata")
        metadata = extract_metadata(path)
        if (title := metadata.get("title")) is not None:
            print(f"Using title '{title}'")
            new_path = path.with_stem(inject_title(path.stem, title))
        else:
            print("Could not get title from metadata")
            # minor QOL - don't leave trailing whitespace
            new_path = path.with_stem(stem_gc(stem_escaped))

    print(f"Rename to:\n'{new_path}' ?")
    if confirm():
        return new_path

    return None


def main() -> int:
    """
    Main entry point
    """
    global ASSUME_YES

    parser = ArgumentParser()
    parser.add_argument("dirs",
                        nargs="+",
                        help="Directory where to start renaming")
    parser.add_argument("-y", "--yes",
                        action="store_true",
                        dest="assume_yes",
                        help="Assume yes for all questions")

    args = parser.parse_args()

    if args.assume_yes:
        ASSUME_YES = True

    for d in args.dirs:
        root = Path(d)

        if not root.is_dir():
            print(f"Specified directory does not exist: {d}")
            return ENOENT

        root = root.absolute()
        walker = root.walk(top_down=True, follow_symlinks=False)

        for dirpath, dirnames, filenames in walker:
            for i in range(len(dirnames)):
                path = dirpath / dirnames[i]
                if (fixed := fix_path(path)) is not None:
                    path.rename(fixed)
                    dirnames[i] = fixed.name

            for i in range(len(filenames)):
                path = dirpath / filenames[i]
                if (fixed := fix_path(path)) is not None:
                    path.rename(fixed)
                    filenames[i] = fixed.name

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
